FROM java:8-alpine
RUN apk add --no-cache bash && \
    apk add --no-cache curl && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    apk del tzdata
