from ${fromImageName}
LABEL go.release.trigger.user=${goReleaseTiggerUser}
LABEL go.release.pipeline.name=${goReleasePipelineName}
LABEL go.release.pipeline.label=${goReleasePipelineLabel}
LABEL go.stage=release